create table "public"."entities" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."entities" enable row level security;

create table "public"."entities_fields" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "field_id" bigint not null,
    "entity_id" bigint not null
);


alter table "public"."entities_fields" enable row level security;

create table "public"."field_types" (
    "id" bigint generated by default as identity not null,
    "type" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."field_types" enable row level security;

create table "public"."fields" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "field_type_id" bigint not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."fields" enable row level security;

CREATE UNIQUE INDEX "entitiesFields_pkey" ON public.entities_fields USING btree (id);

CREATE UNIQUE INDEX entities_pkey ON public.entities USING btree (id);

CREATE UNIQUE INDEX field_pkey ON public.fields USING btree (id);

CREATE UNIQUE INDEX field_type_pkey ON public.field_types USING btree (id);

alter table "public"."entities" add constraint "entities_pkey" PRIMARY KEY using index "entities_pkey";

alter table "public"."entities_fields" add constraint "entitiesFields_pkey" PRIMARY KEY using index "entitiesFields_pkey";

alter table "public"."field_types" add constraint "field_type_pkey" PRIMARY KEY using index "field_type_pkey";

alter table "public"."fields" add constraint "field_pkey" PRIMARY KEY using index "field_pkey";

alter table "public"."entities_fields" add constraint "entitiesFields_entity_id_fkey" FOREIGN KEY (entity_id) REFERENCES entities(id) not valid;

alter table "public"."entities_fields" validate constraint "entitiesFields_entity_id_fkey";

alter table "public"."entities_fields" add constraint "entitiesFields_field_id_fkey" FOREIGN KEY (field_id) REFERENCES fields(id) not valid;

alter table "public"."entities_fields" validate constraint "entitiesFields_field_id_fkey";

alter table "public"."fields" add constraint "field_field_type_id_fkey" FOREIGN KEY (field_type_id) REFERENCES field_types(id) not valid;

alter table "public"."fields" validate constraint "field_field_type_id_fkey";

grant delete on table "public"."entities" to "anon";

grant insert on table "public"."entities" to "anon";

grant references on table "public"."entities" to "anon";

grant select on table "public"."entities" to "anon";

grant trigger on table "public"."entities" to "anon";

grant truncate on table "public"."entities" to "anon";

grant update on table "public"."entities" to "anon";

grant delete on table "public"."entities" to "authenticated";

grant insert on table "public"."entities" to "authenticated";

grant references on table "public"."entities" to "authenticated";

grant select on table "public"."entities" to "authenticated";

grant trigger on table "public"."entities" to "authenticated";

grant truncate on table "public"."entities" to "authenticated";

grant update on table "public"."entities" to "authenticated";

grant delete on table "public"."entities" to "service_role";

grant insert on table "public"."entities" to "service_role";

grant references on table "public"."entities" to "service_role";

grant select on table "public"."entities" to "service_role";

grant trigger on table "public"."entities" to "service_role";

grant truncate on table "public"."entities" to "service_role";

grant update on table "public"."entities" to "service_role";

grant delete on table "public"."entities_fields" to "anon";

grant insert on table "public"."entities_fields" to "anon";

grant references on table "public"."entities_fields" to "anon";

grant select on table "public"."entities_fields" to "anon";

grant trigger on table "public"."entities_fields" to "anon";

grant truncate on table "public"."entities_fields" to "anon";

grant update on table "public"."entities_fields" to "anon";

grant delete on table "public"."entities_fields" to "authenticated";

grant insert on table "public"."entities_fields" to "authenticated";

grant references on table "public"."entities_fields" to "authenticated";

grant select on table "public"."entities_fields" to "authenticated";

grant trigger on table "public"."entities_fields" to "authenticated";

grant truncate on table "public"."entities_fields" to "authenticated";

grant update on table "public"."entities_fields" to "authenticated";

grant delete on table "public"."entities_fields" to "service_role";

grant insert on table "public"."entities_fields" to "service_role";

grant references on table "public"."entities_fields" to "service_role";

grant select on table "public"."entities_fields" to "service_role";

grant trigger on table "public"."entities_fields" to "service_role";

grant truncate on table "public"."entities_fields" to "service_role";

grant update on table "public"."entities_fields" to "service_role";

grant delete on table "public"."field_types" to "anon";

grant insert on table "public"."field_types" to "anon";

grant references on table "public"."field_types" to "anon";

grant select on table "public"."field_types" to "anon";

grant trigger on table "public"."field_types" to "anon";

grant truncate on table "public"."field_types" to "anon";

grant update on table "public"."field_types" to "anon";

grant delete on table "public"."field_types" to "authenticated";

grant insert on table "public"."field_types" to "authenticated";

grant references on table "public"."field_types" to "authenticated";

grant select on table "public"."field_types" to "authenticated";

grant trigger on table "public"."field_types" to "authenticated";

grant truncate on table "public"."field_types" to "authenticated";

grant update on table "public"."field_types" to "authenticated";

grant delete on table "public"."field_types" to "service_role";

grant insert on table "public"."field_types" to "service_role";

grant references on table "public"."field_types" to "service_role";

grant select on table "public"."field_types" to "service_role";

grant trigger on table "public"."field_types" to "service_role";

grant truncate on table "public"."field_types" to "service_role";

grant update on table "public"."field_types" to "service_role";

grant delete on table "public"."fields" to "anon";

grant insert on table "public"."fields" to "anon";

grant references on table "public"."fields" to "anon";

grant select on table "public"."fields" to "anon";

grant trigger on table "public"."fields" to "anon";

grant truncate on table "public"."fields" to "anon";

grant update on table "public"."fields" to "anon";

grant delete on table "public"."fields" to "authenticated";

grant insert on table "public"."fields" to "authenticated";

grant references on table "public"."fields" to "authenticated";

grant select on table "public"."fields" to "authenticated";

grant trigger on table "public"."fields" to "authenticated";

grant truncate on table "public"."fields" to "authenticated";

grant update on table "public"."fields" to "authenticated";

grant delete on table "public"."fields" to "service_role";

grant insert on table "public"."fields" to "service_role";

grant references on table "public"."fields" to "service_role";

grant select on table "public"."fields" to "service_role";

grant trigger on table "public"."fields" to "service_role";

grant truncate on table "public"."fields" to "service_role";

grant update on table "public"."fields" to "service_role";


